# Generated by Django 4.1.4 on 2023-01-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="facebook", new_name="telegram",
        ),
        migrations.RenameField(
            model_name="profile", old_name="instagram", new_name="tokenized_bank_card",
        ),
        migrations.RemoveField(model_name="profile", name="bio",),
        migrations.RemoveField(model_name="profile", name="twitter",),
        migrations.AddField(
            model_name="profile",
            name="INN",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="mystery_id",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="nalog_status",
            field=models.CharField(
                choices=[
                    ("SZ", "Самозанятый"),
                    ("FL", "Физлицо"),
                    ("IP", "Индивидуальный предприниматель"),
                ],
                default="FL",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="shopmetrics_id",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
